services:
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_KEY}
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    network_mode: host
    volumes:
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:z
      - ./docker/traefik/custom:/etc/traefik/custom:z
      - ./docker/traefik/letsencrypt:/letsencrypt:z
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
