# traefik.yml

api:
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/custom"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    http3:
      advertisedPort: 443
    address: ":443"
    http:
      tls:
        options: modern-tls

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      keyType: "RSA4096"
      storage: /letsencrypt/acme.json
      tlsChallenge: true
  cloudflare:
    acme:
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"  # TESTING ONLY
      email: your-email@yourdomain.com
      storage: /letsencrypt/acme.json  # Simpan di volume persisten
      keyType: EC_P256               # Gunakan ECC untuk performa & keamanan
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 60
          disableChecks: true
          requireAllRNS: true
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  zerossl:
    acme:
      caServer: https://acme.zerossl.com/v2/DV90
      email: your-email@example.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 60
          disableChecks: true
          requireAllRNS: true
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

tls:
  options:
    modern-tls:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true

log:
  level: debug  # for error level logging
  filepath: "/logs/error.log"

accesslog:
  filepath: "/logs/access.log"

